### ISSUE TITLE
after using 3 minutes >> Corrupt JPEG data: 29 extraneous bytes before marker 0xd6 Unsupported marker type 0xac [driftnet] warning: driftnet-XXXXX.jpeg: bogus image (err = 4)

### ISSUE THREAD

**Issue by rielinux** [deiv/driftnet#16]
Need help over here, after using 3 minutes i have this notification:
Corrupt JPEG data: 29 extraneous bytes before marker 0xd6 Unsupported marker type 0xac [driftnet] warning: driftnet-XXXXX.jpeg: bogus image (err = 4)

**Comment by deiv** [comment]
@rielinux Is normal, is a false positive while parsing a non jpeg file.

**Comment by sai203** [comment]
even i got the same error,do any oneknow how to fix it?
