### ISSUE TITLE
Feature Possibility?

### ISSUE THREAD

**Issue by caesartcs** [deiv/driftnet#20]
Is it possible to close out images once you see them in Driftnet?
For ex., if I see a content sensitive picture on driftnet and I want to close it out, is there anyway to click on an X button or something command-line to remove that picture?

Im asking because it will be helpful when doing a live demo.

**Comment by deiv** [comment]
Hi,

Just implemented a new web based interface (very basic) 8f9798954f12be4f51246189db7ac345a858cf9c, that can do that. Take a look.
