### ISSUE TITLE
'gtk/gtk.h' file not found,  make error on mac

### ISSUE THREAD

**Issue by Fight0913** [deiv/driftnet#23]
Making all in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in media
make[3]: Nothing to be done for `all'.
Making all in display
  CC       display.o
display.c:22:10: fatal error: 'gtk/gtk.h' file not found
#include <gtk/gtk.h>
         ^~~~~~~~~~~
1 error generated.
make[3]: *** [display.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

**Comment by tudou0digua** [comment]
@Fight0913 hi, I have the same problem, had you solve this problem?

**Comment by deiv** [comment]
Looks like pkg-config is not pulling the required include paths for gtk:

`-I/usr/include/gtk-2.0 -I/usr/include/atk-1.0 `

 maybe fixed by e5abae731f7781c8bc15666920d8fde02722c076, could you take a look ?

**Comment by deiv** [comment]
Related to #14, closing duplicate.
