### ISSUE TITLE
make error on mac os 10.12 when making all in http_display

### ISSUE THREAD

**Issue by Fykex** [deiv/driftnet#24]
make
Making all in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in media
  CC       media.o
  CC       image.o
  CC       audio.o
  CC       mpeghdr.o
  CC       playaudio.o
  CC       http.o
  AR       libmedia.a
Making all in display
  CC       display.o
  CC       img.o
  CC       gif.o
  CC       jpeg.o
  CC       png.o
  AR       libdisplay.a
Making all in http_display
  CC       httpd.o
rm -f 'web_data.c'
echo '#include "web_data.h"' >> web_data.c
echo '#include <stddef.h>' >> web_data.c
for f in static_web/close.png static_web/index.html static_web/jquery.js static_web/lightbox.min.css static_web/lightbox.min.js static_web/loading.gif static_web/next.png static_web/prev.png ; do \
		echo -n 'unsigned char ' >> web_data.c; \
		basename $f | sed 's@[-. ]@_@g' >> web_data.c; \
		echo '[] = {' >> web_data.c; \
		cat $f | xxd -i >> web_data.c; \
		echo '};' >> web_data.c; \
	done
echo 'web_static_file_t static_content[] = {' >> web_data.c
for f in static_web/close.png static_web/index.html static_web/jquery.js static_web/lightbox.min.css static_web/lightbox.min.js static_web/loading.gif static_web/next.png static_web/prev.png ; do \
			echo '{' >> web_data.c; \
			basename $f | sed 's@\(.*\)@"\1",@g' >> web_data.c; \
			basename $f | sed 's@[-. ]@_@g' >> web_data.c; \
			echo ',' >> web_data.c; \
			cat $f | wc -c >> web_data.c; \
			echo '},' >> web_data.c ;\
	done
echo '{NULL, NULL, 0}};' >> web_data.c
  CC       web_data.o
web_data.c:3:1: error: expected external declaration
-n unsigned char
^
web_data.c:3:2: error: unknown type name 'n'
-n unsigned char
 ^
web_data.c:3:4: error: expected identifier or '('
-n unsigned char

**Comment by deiv** [comment]
Seems that 'echo' command arg '- n' its getting printed into 'web_data.c' generated file. 

May you attach 'web_data.c' file, after make command is executed ?

**Comment by Fykex** [comment]
the web_data.c

**Comment by Fykex** [comment]
@deiv 
The 'web_data.c' file
[web_data.c.zip](https://github.com/deiv/driftnet/files/2292209/web_data.c.zip)

**Comment by Fykex** [comment]
@deiv It works for me, thanks

**Comment by deiv** [comment]
It should be fixed by 0bfaf3c592c28794799873711db1ff3d8a71fee3

@Fykex may you test if now works ? Atm I don't have acess to any mac os version
