### ISSUE TITLE
Error on linux mint:can't start app

### ISSUE THREAD

**Issue by eddisch** [deiv/driftnet#34]
![image](https://user-images.githubusercontent.com/73175017/125192537-aa713280-e248-11eb-8226-dd47c87d2e25.png)

this error I see:
Sun Jul 11 13:02:02 2021 - error: pcap_activate: You don't have permission to capture on that device

how to fix that?

**Comment by deiv** [comment]
Hi,

Driftnet uses libpcap to capture live traffic, so puttin cap on tcpdump will not work (maybe on itself?).

You can run driftnet as root, with sudo (later you can drop privileges to another user with -z switch, if running as non root is a must for you).
