### ISSUE TITLE
can' install 

### ISSUE THREAD

**Issue by july2993** [deiv/driftnet#6]
```
Making all in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in media
make[3]: Nothing to be done for `all'.
Making all in display
  CC       display.o
display.c:23:10: fatal error: 'gtk/gtk.h' file not found
#include <gtk/gtk.h>
         ^
1 error generated.
make[3]: *** [display.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1
```

**Comment by deiv** [comment]
Could you please attach the config.log and config.status files ?

**Comment by july2993** [comment]
the files you want

2015-06-20 2:42 GMT+08:00 David Suárez <notifications@github.com>:

**Comment by july2993** [comment]
seems can't receive the attach file,you can get it from the following link:

[config.log](https://www.dropbox.com/s/eonadihhf3ojuvv/config.log?dl=0)
[config.status](https://www.dropbox.com/s/7s6lgzreqd6947g/config.status?dl=0)

**Comment by deiv** [comment]
Seems that GTK_CFLAGS are not filled with the gtk include headers paths, so the compiler can't find them. For example, on my system, running:
```
$pkg-config --cflags gtk+-x11-2.0 glib-2.0 gobject-2.0 gdk-x11-2.0'
```

Gives: -pthread -I/usr/include/gtk-2.0 -I/usr/include/atk-1.0 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/gtk-2.0 -I/usr/lib/i386-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include

I dunno where's the problem, but most probably if that headers are not installed or pkg-config can't find 'gtk+-2.0.pc' file.

You could try a search for the headers and the 'gtk+-2.0.pc' file. If both are present you could try to export PKG_CONFIG_PATH enviroment variable with the path of the directory that contains the 'gtk+-2.0.pc' file before running ./configure again:

```
export PKG_CONFIG_PATH=/path/to/other-pkgconfig/dir
./configure
```

**Comment by inu1255** [comment]
if you didn't install gtk+, `brew install gtk+`
else reference #8
