### ISSUE TITLE
Install driftnet on Archlinux

### ISSUE THREAD

**Issue by jinjiachen** [deiv/driftnet#9]
hello,  i am compiling driftnet on archlinux,and these some problems i cant figure out,please help me, thanks in advance!!

i have finished the first step: ./configure    and everything is ok for now.
when i executed the second step:  make ,the problem came out. the error information below:

Making all in src
make[1]: Entering directory '/tmp/driftnet-master/src'
make  all-recursive
make[2]: Entering directory '/tmp/driftnet-master/src'
Making all in media
make[3]: Entering directory '/tmp/driftnet-master/src/media'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/tmp/driftnet-master/src/media'
Making all in display
make[3]: Entering directory '/tmp/driftnet-master/src/display'
  CC       gif.o
gif.c: 在函数‘gif_abort_load’中:
gif.c:50:5: 错误：提供给函数‘DGifCloseFile’的实参太少
     DGifCloseFile((GifFileType*)I->us);
     ^
In file included from gif.c:18:0:
/usr/include/gif_lib.h:183:9: 附注：在此声明
     int DGifCloseFile(GifFileType * GifFile, int *ErrorCode);
         ^
gif.c: 在函数‘gif_load_img’中:
gif.c:128:5: 错误：提供给函数‘DGifCloseFile’的实参太少
     DGifCloseFile(g);
     ^
In file included from gif.c:18:0:
/usr/include/gif_lib.h:183:9: 附注：在此声明
     int DGifCloseFile(GifFileType * GifFile, int *ErrorCode);
         ^
Makefile:319: recipe for target 'gif.o' failed
make[3]: *** [gif.o] Error 1
make[3]: Leaving directory '/tmp/driftnet-master/src/display'
Makefile:450: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/tmp/driftnet-master/src'
Makefile:316: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/tmp/driftnet-master/src'
Makefile:395: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

i can't figure out it by myself, please help me, thanks

**Comment by deiv** [comment]
Hi,

Related to giflib >= 5 changes. Fixed in d4b1f252

Thanks for the report
